services:
  web:
    container_name: web
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./packages:/app/packages
      - /app/node_modules
    networks:
      - the_marketplace_network
    develop:
      watch:
        - action: sync
          path: ./apps/web/src
          target: /app/apps/web/src
          ignore:
            - node_modules/
            - build/
        - action: rebuild
          path: ./apps/web/package.json
  api:
    container_name: api
    environment:
      API_PORT: ${API_PORT}
      API_NODE_ENV: ${API_NODE_ENV}
      API_DB_HOST: ${API_DB_HOST}
      API_DB_PORT: ${API_DB_PORT}
      API_DB_DATABASE: ${API_DB_DATABASE}
      API_DB_USERNAME: ${API_DB_USERNAME}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_JWT_SECRET: ${API_JWT_SECRET}
      WEB_URL: ${WEB_URL}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./packages:/app/packages
    networks:
      - the_marketplace_network
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/apps/api/src
          ignore:
            - node_modules/
            - build/
        - action: rebuild
          path: ./apps/api/package.json
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${API_DB_DATABASE}
      POSTGRES_USER: ${API_DB_USERNAME}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - the_marketplace_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  the_marketplace_network:
    driver: bridge

volumes:
  postgres_data:
